package io.openems.edge.meter.socomec.digiware.iac;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;
import io.openems.edge.meter.socomec.digiware.LoadSelection;

@ObjectClassDefinition(//
		name = "Meter Socomec Digiware I-AC", //
		description = "Implements the Socomec Digiware I-AC")
public
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Load Selection", description = "Select which load (1-6) this meter represents")
	LoadSelection loadSelection() default LoadSelection.LOAD_1;

	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.CONSUMPTION_METERED;

	@AttributeDefinition(name = "Invert Power", description = "Inverts all Power values, i.e. Power is multiplied with -1.")
	boolean invert() default false;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(name = "State Channel Rules", description = "JSON array of threshold-based StateChannel rules. "
			+ "Each entry: {\"channelId\":\"ACTIVE_POWER\",\"condition\":\"GREATER_THAN\","
			+ "\"threshold\":5000,\"name\":\"HIGH_POWER\",\"level\":\"WARNING\",\"description\":\"...\"}. "
			+ "Leave as '[]' to disable.")
	String stateChannelRules() default "[]";

	String webconsole_configurationFactory_nameHint() default "Meter Socomec Digiware I-AC [{id}]";

}